require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "soy.gemspec"
    - "spec/**/*.rb"

Metrics/MethodLength:
  Max: 20

RSpec/MultipleExpectations:
  Enabled: false
