#!/usr/bin/env ruby
# frozen_string_literal: true

require "sito"

require "optparse"

first_arg = ARGV[0]
case first_arg
when "build"
  puts "Building site..."
  Sito.build(ARGV[1])
  puts "Site successfully built"
when "help", "h", nil
  puts "Sito CLI"
  puts "Available commands:\n"
  puts "\tbuild - generate site in the build directory"
  puts "\tversion - current version of the library"
when "version", "v"
  puts Sito::VERSION
else
  puts "`#{first_arg}` is not a command"
  puts "Run `sito help` for list of commands"
end
