#!/usr/bin/env ruby
# frozen_string_literal: true

require "soy"

def elapsed
  starting = Process.clock_gettime(Process::CLOCK_MONOTONIC)
  yield
  ending = Process.clock_gettime(Process::CLOCK_MONOTONIC)
  (ending - starting).round(6)
end

first_arg = ARGV[0]
case first_arg
when "build", "b"
  puts "Building site..."
  time = elapsed do
    Soy.build(ARGV[1])
  end
  puts "Site successfully built in #{time} seconds"
when "help", "h", "-h", "--help", nil
  puts "Soy CLI"
  puts "Available commands:\n"
  puts "\tbuild (b) - generate site in the build directory"
  puts "\tserver (s) - rebuild site on changes and start HTTP server"
  puts "\tversion (v) - current version of the library"
when "server", "serve", "s"
  Soy::Server.start(ARGV[1])
when "version", "v"
  puts Soy::VERSION
else
  puts "`#{first_arg}` is not a command"
  puts "Run `soy help` for list of commands"
end
